// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.gfu.seminar.spring.domain;

import net.gfu.seminar.spring.domain.GuestIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect GuestIntegrationTest_Roo_Configurable {
    
    declare @type: GuestIntegrationTest: @Configurable;
    
}
