// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.gfu.seminar.spring.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import net.gfu.seminar.spring.domain.Guest;
import net.gfu.seminar.spring.domain.GuestDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect GuestDataOnDemand_Roo_DataOnDemand {
    
    declare @type: GuestDataOnDemand: @Component;
    
    private Random GuestDataOnDemand.rnd = new SecureRandom();
    
    private List<Guest> GuestDataOnDemand.data;
    
    public Guest GuestDataOnDemand.getNewTransientGuest(int index) {
        Guest obj = new Guest();
        setFirstname(obj, index);
        setLastname(obj, index);
        return obj;
    }
    
    public void GuestDataOnDemand.setFirstname(Guest obj, int index) {
        String firstname = "firstname_" + index;
        obj.setFirstname(firstname);
    }
    
    public void GuestDataOnDemand.setLastname(Guest obj, int index) {
        String lastname = "lastname_" + index;
        obj.setLastname(lastname);
    }
    
    public Guest GuestDataOnDemand.getSpecificGuest(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Guest obj = data.get(index);
        Long id = obj.getId();
        return Guest.findGuest(id);
    }
    
    public Guest GuestDataOnDemand.getRandomGuest() {
        init();
        Guest obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Guest.findGuest(id);
    }
    
    public boolean GuestDataOnDemand.modifyGuest(Guest obj) {
        return false;
    }
    
    public void GuestDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Guest.findGuestEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Guest' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Guest>();
        for (int i = 0; i < 10; i++) {
            Guest obj = getNewTransientGuest(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
